name: gitStream deployments
run-name: gitStream deployment `${{ github.ref_name }}` to `${{ inputs.env }}`

on:
  repository_dispatch:
    types: [deploy]

  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: the env you want to deploy to
        options:
          - dev-01
          - prod

concurrency:
  group: deploy_${{ inputs.env }}
  cancel-in-progress: false

jobs:
  deploy-to-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CLI
        run: |
          echo "Deploying to ${{ inputs.env }}"
          echo "Running CLI command"
          echo "gitStream deploy --env ${{ inputs.env }} --tag ${{ github.ref_name }}"
