name: check action-slack-notify

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  TAG_URL: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}

jobs:
  deploy-to-env:
    runs-on: ubuntu-24.04
    steps:
      # - uses: actions/checkout@v4

      - name: Success Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: gitstream-rules-resolver
          SLACK_FOOTER: <${{ env.WORKFLOW_RUN_URL }}|workflow run> | <${{ env.TAG_URL }}|${{ github.ref_name }}>
          SLACK_MESSAGE: |
            Deployed `1.0.2` to `prod`
            Linbee-13969 rules resolver create auto deployment workflow 2 by @MishaKav in \n feat(lambda): increase memory size for jwtAuthorizer function to 128 MB by @MishaKav
