name: check action-slack-notify

on:
  push:
    branches:
      - action-slack-notify

  workflow_dispatch:

env:
  WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  TAG_URL: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}

jobs:
  deploy-to-env:
    runs-on: ubuntu-24.04
    steps:
      # - uses: actions/checkout@v4

      - name: Success Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ${{ github.repository }}
          SLACK_FOOTER: <${{ env.WORKFLOW_RUN_URL }}|workflow run> | <${{ env.TAG_URL }}|${{ github.ref_name }}>
          SLACK_MESSAGE: |
            Deployed `${{ github.ref_name }}` to `dev-01`
            some custom text for second line
