name: Run 5 Automations with Delay

on:
  pull_request:

jobs:
  automation-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: [1, 2, 3, 4, 5]
    steps:
      - name: Wait for ${{ matrix.item }} seconds
        run: |
          echo "Waiting for ${{ matrix.item }} seconds..."
          sleep ${{ matrix.item }}
          echo "Wait ${{ matrix.item }} completed!"