name: Run 3 Automations with Delay

on:
  pull_request:

jobs:
  automation-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: [1, 2]

    steps:
      - name: Wait for ${{ matrix.item }} seconds
        run: |
          echo "Waiting for 120 seconds for matrix ${{ matrix.item }}..."
          sleep 120
          echo "Wait ${{ matrix.item }} completed!"
