name: Create Tag on Merge and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Create and push new tag
        id: create-tag
        run: |
          npm run create-tag

      - name: Get latest commit
        id: get-commit
        run: echo "LAST_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Check for associated pull request and auto-release label
        id: should-release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const commit_sha = '${{ env.LAST_SHA }}';
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({ commit_sha, owner, repo });

            if (prs?.length > 0) {
              const pull_number = prs[0].number;
              const { data: pr } = await github.rest.pulls.get({ owner, repo, pull_number });
              return pr.labels.some(label => label.name.includes('auto-release'));
            }
            return false;

      - name: Create GitHub Release
        if: steps.should-release.outputs.result == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ steps.create-tag.outputs.new_tag }}
        run: |
          gh release create $NEW_TAG --generate-notes
